# Generated by Django 5.1.4 on 2024-12-31 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_blog', '0002_alter_post_options_post_excerpt_post_updated_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('author', models.ForeignKey
                 (on_delete=django.db.models.deletion.CASCADE,
                  related_name='commenter', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey
                 (on_delete=django.db.models.deletion.CASCADE,
                  related_name='comments', to='fin_blog.post')),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
