# Generated by Django 5.1.4 on 2024-12-31 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_blog', '0004_category_post_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
    ]
