# Generated by Django 5.1.4 on 2025-01-07 15:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fin_blog', '0007_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default='default_rolq52', max_length=255, verbose_name='image'),
        ),
    ]
