# Generated by Django 5.1.4 on 2025-01-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_blog', '0008_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
    ]
