# Generated by Django 5.1.4 on 2025-01-09 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_blog', '0011_alter_category_author_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pending_deletion',
            field=models.BooleanField(default=False),
        ),
    ]
